id: opecha:P005386
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4726
  title: མངོན་རྟོགས་རྒྱན་གྱི་གཞུང་སྔ་ཕྱིའི་འབྲེལ་བ་དང་དཀའ་གནས་ལ་དཔྱད་པ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད།
  volume: ''
  author: ''
