id: IAB294A23
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:25:41+00:00'
last_modified: '2022-06-08T02:43:02.664071+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4726
  title: མངོན་རྟོགས་རྒྱན་གྱི་གཞུང་སྔ་ཕྱིའི་འབྲེལ་བ་དང་དཀའ་གནས་ལ་དཔྱད་པ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E498:
      image_group_id: I3CN4728
      title: ''
      total_pages: 400
      order: 1
      base_file: E498.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
